apiVersion: iot.enmasse.io/v1alpha1
kind: IoTConfig
metadata:
  name: default
spec:
  enableDefaultRoutes: true
  interServiceCertificates:
    secretCertificatesStrategy:
      caSecretName: iot-service-ca
      serviceSecretNames:
        iot-auth-service: iot-auth-service-tls
        iot-device-connection: iot-device-connection-tls
        iot-device-registry: iot-device-registry-tls
        iot-tenant-service: iot-tenant-service-tls
        iot-mesh-inter: iot-mesh-inter-tls
        iot-command-mesh: iot-command-mesh-tls
  services:
    deviceConnection:
      jdbc:
        server:
          external:
            username: registry
            password: user12
            url: jdbc:postgresql://postgresql/device-registry
    deviceRegistry:
      jdbc:
        server:
          external:
            management:
              connection:
                username: registry
                password: user12
                url: jdbc:postgresql://postgresql/device-registry
      management:
        endpoint:
          secretNameStrategy:
            secretName: iot-device-registry-tls
  adapters:
    amqp:
      endpoint:
        secretNameStrategy:
          secretName: iot-amqp-adapter-tls
    http:
      endpoint:
        secretNameStrategy:
          secretName: iot-http-adapter-tls
    mqtt:
      endpoint:
        secretNameStrategy:
          secretName: iot-mqtt-adapter-tls
    sigfox:
      endpoint:
        secretNameStrategy:
          secretName: iot-sigfox-adapter-tls
    lorawan:
      endpoint:
        secretNameStrategy:
          secretName: iot-lorawan-adapter-tls