kind: ConfigMap
apiVersion: v1
metadata:
  name: infinispan-configuration
data:
  infinispan.yml: |
    infinispan:
      clusterName: infinispan
    endpoints:
      hotrod:
        enabled: true
        qop: auth
        serverName: infinispan
      memcached:
        enabled: false
      rest:
        enabled: true
    jgroups:
      transport: tcp
      dnsPing:
        query: infinispan-dns-ping.enmasse-infra.svc.cluster.local

