kind: ConfigMap
apiVersion: v1
metadata:
  name: infinispan-configuration
data:
  infinispan.yml: |
    infinispan:
      clusterName: infinispan
    endpoints:
      hotrod:
        enabled: true
        qup: auth
        serverName: infinispan
      memcached:
        enabled: false
      rest:
        enabled: true
    jgroups:
      transport: tcp
      dnsPing:
        query: infinispan-dns-ping.myproject.svc.cluster.local

