kind: ConfigMap
apiVersion: v1
metadata:
  name: infinispan-readyness-script
data:
  readyness.sh: |
    #!/bin/bash
    set -e

    HOSTNAME=$(cat /etc/hosts | grep -m 1 $(cat /proc/sys/kernel/hostname) | awk '{print $1;}')
    PROBE_URL=http://${HOSTNAME}:11222/rest/v2/cache-managers/clustered/health/status

    curl --http1.1 --insecure --fail --silent --show-error -X GET ${PROBE_URL} | grep -q "HEALTHY"