apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan-ping # align name with operator version
spec:
  clusterIP: None
  ports:
  - port: 7800
    targetPort: 7800
    name: ping
  selector:
    name: infinispan
    app: infinispan
