kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  labels:
    name: infinispan
    app: infinispan
  name: infinispan
spec:
  replicas: 1
  serviceName: infinispan-server-headless
  selector:
    matchLabels:
      name: infinispan
      app: infinispan
  template:
    metadata:
      labels:
        name: infinispan
        app: infinispan
      name: infinispan
    spec:
      serviceAccount: infinispan
      containers:
      - command: [/opt/infinispan/bin/server.sh]
        args:
        - -b 
        - SITE_LOCAL
        - -c
        - /config/custom-infinispan.xml
        - -Djgroups.dns.query=infinispan.enmasse-infra.svc.cluster.local
        env:
        - name: KUBERNETES_LABELS
          value: app=infinispan,name=infinispan
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              name: conn-auth-secret
              key: username
        - name: APP_PASS
          valueFrom:
            secretKeyRef:
              name: conn-auth-secret
              key: password
        - name: MGMT_USER
          valueFrom:
            secretKeyRef:
              name: mgmt-auth-secret
              key: username
        - name: MGMT_PASS
          valueFrom:
            secretKeyRef:
              name: mgmt-auth-secret
              key: password
        image: quay.io/infinispan/server:10.0.1.Final
        name: infinispan-server
        ports:
        - containerPort: 8888
          name: ping
          protocol: TCP
        - containerPort: 11222
          name: infinispan
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /opt/infinispan/bin/livenessProbe.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 80
        readinessProbe:
          exec:
            command:
            - /opt/infinispan/bin/readinessProbe.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 80
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: infinispan-configuration
        - mountPath: /opt/infinispan/server/data
          name: infinispan-data
      terminationGracePeriodSeconds: 120
      volumes:
      - name: infinispan-configuration
        configMap:
          defaultMode: 420
          name: infinispan-configuration
  volumeClaimTemplates:
  - metadata:
      name: infinispan-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
